server.port: 8081
spring:
  application.name: movie-catalog-service
  profiles.active: test
management.endpoints.web.exposure.include: hystrix.stream

greeting.message: Hello

# can refer to other property
app:
  name: "My App"
  desc: "Welcome to ${app.name}"

my.list.values: One,Two,Three

dbValues: "{connectionString: 'http://----', username: 'uname', password: 'pass'}"

db:
  connection: "{connectionString: 'http://----', username: 'uname', password: 'pass'}"
  host: 127.0.0.1
  port: 5432